### ISSUE TITLE
Unable to load model in nodejs

### ISSUE THREAD

**Issue by LittleRobertTables** [ccoreilly/vosk-browser#18]
When I run the following code:
```js
let Vosk = require("vosk-browser");
let url = "model.tar.gz";
async function init() {
  const model = await Vosk.createModel(url);
}
init();
```
I get this error:
```
this.worker.addEventListener("message", (event) => this.handleMessage(event));
                   ^

TypeError: this.worker.addEventListener is not a function
    at EventTarget.initialize (/Users/bobby/Desktop/vosk-browser/node_modules/vosk-browser/dist/vosk.js:238:25)
    at new Model (/Users/bobby/Desktop/vosk-browser/node_modules/vosk-browser/dist/vosk.js:235:18)
    at Object.<anonymous> (/Users/bobby/Desktop/vosk-browser/node_modules/vosk-browser/dist/vosk.js:354:27)
    at Generator.next (<anonymous>)
    at /Users/bobby/Desktop/vosk-browser/node_modules/vosk-browser/dist/vosk.js:28:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/bobby/Desktop/vosk-browser/node_modules/vosk-browser/dist/vosk.js:24:16)
    at Object.createModel (/Users/bobby/Desktop/vosk-browser/node_modules/vosk-browser/dist/vosk.js:353:16)
    at init (/Users/bobby/Desktop/vosk-browser/index.js:5:28)
    at Object.<anonymous> (/Users/bobby/Desktop/vosk-browser/index.js:7:1)
```

My folder structure is 
```
|
|-- index.js
|-- model.tar.gz
|-- node_modules/
```
So I would thing the program could load the model, but I also get the same error when I set the url to be complete gibberish.

Thanks for your help

**Comment by LittleRobertTables** [comment]
I get the same error with:
```js
let Vosk = require("vosk-browser");
let url = "model.tar.gz";
async function init() {
  const model = new Vosk.Model(url);
}
init();
```

**Comment by ccoreilly** [comment]
The WASM build targets running in a web worker. As stated in the readme you should use the official node bindings if running vosk from nodejs.

**Comment by LittleRobertTables** [comment]
Ah, I was hoping this would be possible. I'm working on an arm-based machine and the node-bindings currently only support x86. Oh well, projects still super cool.

**Comment by ccoreilly** [comment]
Oh, I see. You can compile the WASM binary yourself and remove the limitation of it running in a WebWorker environment. 
For that
- first create the builder image running `make builder`
- then remove the line `-s ENVIRONMENT=worker` from `src/Makefile` and run `make binary`

You'll end up with a `vosk-wasm.js` in `build/release` which you can `require` in your node application. The interface is nearly the same as vosk (you can reference the typescript definition in `src/vosk.d.ts`

I hope it helps!
